apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '10'
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/3yR3W4aMRCF32Wu96cLC8vuHSqoqpQmETTtRRVFY88ATvzXtZeKon33ylEbUSniyrLPnPPNjM+AXn3jPihnoQP0PpTHCjJ4UZaggxV77U6GbYQMDEckjAjdGdBaFzEqZ0O6OvHMMgaORa9cITFGzYVypUohLdaNqHe7HHfzNq9pRrloSeY0X7SzhptK0ATGDDQK1lfjDhgO0MGHZjppZk2FNBNE82ndcsMLEovFhNtpzVxxRVQ1KdSiYeggDP2RTzl6n9PlTEkOHmWqId7hoGNyBc8yNdKz10pigK7KILBmGV2fBINRHm7eGkbv/4PAOGYQ2XiNkV/rL3anr9v+saWzEZXlPkD34wxsj6/n34G295vPt5+eVsuvy+3dw+bj+ulhcwMZHFEPSX8mITtzCj91V5Z7M0QOkUQhRT09uF14kWJfDCFnDDGvip5CgQZ/O4u/QiGdKWHMrrG2683t8sv6AvjGuO68X2633+82q/edjxkog/v0atAS9nJelxf7eec/YXwcx3H8EwAA///nroWAygIAAA
    objectset.rio.cattle.io/id: 9a47b4ff-af69-4d5d-b9dc-d68957e71bd2
  creationTimestamp: '2023-11-23T16:50:21Z'
  generation: 10
  labels:
    objectset.rio.cattle.io/hash: 07327571ad5bdd6349e7e8db882e934ee1e1dd17
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:app: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"swe"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"SPRING_DATASOURCE_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SPRING_DATASOURCE_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SPRING_DATASOURCE_USERNAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: agent
      operation: Update
      time: '2023-11-24T00:59:53Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"swe"}:
                  f:image: {}
      manager: kubectl-set
      operation: Update
      time: '2023-11-24T15:27:23Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2023-12-01T01:23:43Z'
  name: survey-app-deployment
  namespace: default
  resourceVersion: '2272925'
  uid: c80873fa-a919-47e4-ae0f-11915aa17d85
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: survey-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-11-24T00:59:53Z'
      creationTimestamp: null
      labels:
        app: survey-app
      namespace: default
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: >-
                jdbc:mysql://gmutestdb.cb43hofskcbg.us-east-1.rds.amazonaws.com/gmutestdb
            - name: SPRING_DATASOURCE_USERNAME
              value: gmutestdb
            - name: SPRING_DATASOURCE_PASSWORD
              value: gmutestdb
          image: mandarc64/swe:2023-11-24_15-26-52
          imagePullPolicy: Always
          name: swe
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-11-23T16:50:21Z'
      lastUpdateTime: '2023-11-24T15:27:27Z'
      message: >-
        ReplicaSet "survey-app-deployment-758b8cb774" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2023-12-01T01:23:43Z'
      lastUpdateTime: '2023-12-01T01:23:43Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

